//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Championship {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Championship() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Validations.Championship.Championship", typeof(Championship).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato cadastrado.
        /// </summary>
        public static string ChampionshipAdded {
            get {
                return ResourceManager.GetString("ChampionshipAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Final não pode ser vazio..
        /// </summary>
        public static string FinalDateNotNull {
            get {
                return ResourceManager.GetString("FinalDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser posterior à data final..
        /// </summary>
        public static string FinalDateRange {
            get {
                return ResourceManager.GetString("FinalDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser vazio..
        /// </summary>
        public static string InitialDateNotNull {
            get {
                return ResourceManager.GetString("InitialDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser anterior a hoje..
        /// </summary>
        public static string InitialDateRange {
            get {
                return ResourceManager.GetString("InitialDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome deve ter entre 4 e 50 caracteres..
        /// </summary>
        public static string NameCharRange {
            get {
                return ResourceManager.GetString("NameCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome não pode ser vazio..
        /// </summary>
        public static string NameNotNull {
            get {
                return ResourceManager.GetString("NameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Prêmio deve ter entre 3 e 20 caracteres..
        /// </summary>
        public static string PrizeCharRange {
            get {
                return ResourceManager.GetString("PrizeCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Prêmio não pode ser vazio..
        /// </summary>
        public static string PrizeNotNull {
            get {
                return ResourceManager.GetString("PrizeNotNull", resourceCulture);
            }
        }
    }
}
