//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Championship {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Championship() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Validations.Championship.Championship", typeof(Championship).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato cadastrado.
        /// </summary>
        public static string ChampionshipAdded {
            get {
                return ResourceManager.GetString("ChampionshipAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver pelo menos 10 caracteres na descrição, e no máximo 10 mil caracteres..
        /// </summary>
        public static string ChampionshipValidatorAtleast10 {
            get {
                return ResourceManager.GetString("ChampionshipValidatorAtleast10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver pelo menos 2 times no campeonato..
        /// </summary>
        public static string ChampionshipValidatorAtleastTwo {
            get {
                return ResourceManager.GetString("ChampionshipValidatorAtleastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Cidade não pode estar vazia..
        /// </summary>
        public static string ChampionshipValidatorCityNotNull {
            get {
                return ResourceManager.GetString("ChampionshipValidatorCityNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Esporte deve ser preenchido com Vôlei ou futebol..
        /// </summary>
        public static string ChampionshipValidatorFootballOrVolley {
            get {
                return ResourceManager.GetString("ChampionshipValidatorFootballOrVolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de times deve ser um quadrado de 2, como 4, 16, 32, 64, etc..
        /// </summary>
        public static string ChampionshipValidatorInvalidQuantity {
            get {
                return ResourceManager.GetString("ChampionshipValidatorInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de times não pode exceder 128 times..
        /// </summary>
        public static string ChampionshipValidatorMaximumQuantityExceeded {
            get {
                return ResourceManager.GetString("ChampionshipValidatorMaximumQuantityExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo País não pode estar vazio..
        /// </summary>
        public static string ChampionshipValidatorNationNotNull {
            get {
                return ResourceManager.GetString("ChampionshipValidatorNationNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Bairro não pode estar vazio..
        /// </summary>
        public static string ChampionshipValidatorNeighborhoodNotNull {
            get {
                return ResourceManager.GetString("ChampionshipValidatorNeighborhoodNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Número de Jogadores não pode estar vazio..
        /// </summary>
        public static string ChampionshipValidatorNumberOfPlayers {
            get {
                return ResourceManager.GetString("ChampionshipValidatorNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Esporte não pode ser vazio..
        /// </summary>
        public static string ChampionshipValidatorSportNotNull {
            get {
                return ResourceManager.GetString("ChampionshipValidatorSportNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Estado não pode estar vazio..
        /// </summary>
        public static string ChampionshipValidatorStateNotNull {
            get {
                return ResourceManager.GetString("ChampionshipValidatorStateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato excluido com sucesso.
        /// </summary>
        public static string DeleteDeleted {
            get {
                return ResourceManager.GetString("DeleteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão para excluir um campeonato.
        /// </summary>
        public static string DeleteNotAuthorized {
            get {
                return ResourceManager.GetString("DeleteNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Final não pode ser vazio..
        /// </summary>
        public static string FinalDateNotNull {
            get {
                return ResourceManager.GetString("FinalDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser posterior à data final..
        /// </summary>
        public static string FinalDateRange {
            get {
                return ResourceManager.GetString("FinalDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser vazio..
        /// </summary>
        public static string InitialDateNotNull {
            get {
                return ResourceManager.GetString("InitialDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Inicial não pode ser anterior a hoje..
        /// </summary>
        public static string InitialDateRange {
            get {
                return ResourceManager.GetString("InitialDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome deve ter entre 4 e 50 caracteres..
        /// </summary>
        public static string NameCharRange {
            get {
                return ResourceManager.GetString("NameCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome não pode ser vazio..
        /// </summary>
        public static string NameNotNull {
            get {
                return ResourceManager.GetString("NameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome Artístico não pode ser vazio..
        /// </summary>
        public static string PlayerValidatorArtisticNameNotNull {
            get {
                return ResourceManager.GetString("PlayerValidatorArtisticNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Prêmio deve ter entre 3 e 20 caracteres..
        /// </summary>
        public static string PrizeCharRange {
            get {
                return ResourceManager.GetString("PrizeCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Prêmio não pode ser vazio..
        /// </summary>
        public static string PrizeNotNull {
            get {
                return ResourceManager.GetString("PrizeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato com esse ID não existe.
        /// </summary>
        public static string ShowCampeonatoIdNaoExiste {
            get {
                return ResourceManager.GetString("ShowCampeonatoIdNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato atualizado com sucesso.
        /// </summary>
        public static string UpdateCampeonatoAtualizadoComSucesso {
            get {
                return ResourceManager.GetString("UpdateCampeonatoAtualizadoComSucesso", resourceCulture);
            }
        }
    }
}
