//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources.Validations.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Validations.User.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário possuir pelo menos 13 anos de idade para se cadastrar.
        /// </summary>
        public static string UserValidatorAtleast13 {
            get {
                return ResourceManager.GetString("UserValidatorAtleast13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Bio pode ter no máximo 300 caracteres..
        /// </summary>
        public static string UserValidatorBioInvalidLength {
            get {
                return ResourceManager.GetString("UserValidatorBioInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CPF não pode ser vazio..
        /// </summary>
        public static string UserValidatorCpfNotNull {
            get {
                return ResourceManager.GetString("UserValidatorCpfNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe sua data de nascimento.
        /// </summary>
        public static string UserValidatorDateBirthNotNull {
            get {
                return ResourceManager.GetString("UserValidatorDateBirthNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email inválido.
        /// </summary>
        public static string UserValidatorInvalidEmail {
            get {
                return ResourceManager.GetString("UserValidatorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CPF deve ter 11 caracteres..
        /// </summary>
        public static string UserValidatorInvalidLength {
            get {
                return ResourceManager.GetString("UserValidatorInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve possuir pelo menos 4 caracteres e no máximo 200..
        /// </summary>
        public static string UserValidatorInvalidNameLength {
            get {
                return ResourceManager.GetString("UserValidatorInvalidNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string UserValidatorInvalidPassword {
            get {
                return ResourceManager.GetString("UserValidatorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário inválido, seu nome de usuário deve conter apenas letras maíusculas, minúsculas, números e opcionalmente &quot;&quot;-&quot;&quot;,&quot;&quot;_&quot;&quot;. Assim como deve possuir pelo menos 4 caracteres e no máximo 100..
        /// </summary>
        public static string UserValidatorInvalidUsername {
            get {
                return ResourceManager.GetString("UserValidatorInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o seu nome.
        /// </summary>
        public static string UserValidatorNameNotNull {
            get {
                return ResourceManager.GetString("UserValidatorNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos CPF deve conter apenas números.
        /// </summary>
        public static string UserValidatorOnlyNumbers {
            get {
                return ResourceManager.GetString("UserValidatorOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira sua senha.
        /// </summary>
        public static string UserValidatorPasswordNotNull {
            get {
                return ResourceManager.GetString("UserValidatorPasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe seu nome de usuário, ele será utilizado para permitir que outros usuários o identifiquem sem revelar seu nome.
        /// </summary>
        public static string UserValidatorUsernameNotNull {
            get {
                return ResourceManager.GetString("UserValidatorUsernameNotNull", resourceCulture);
            }
        }
    }
}
