//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChampionshipService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChampionshipService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Services.ChampionshipService", typeof(ChampionshipService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido cadastrar um campeonato sem um CPF cadastrado..
        /// </summary>
        internal static string CreateValidationAsyncCpfNotNull {
            get {
                return ResourceManager.GetString("CreateValidationAsyncCpfNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de jogadores inválido para futebol. Deve haver no mínimo 11 jogadores num time de futebol..
        /// </summary>
        internal static string CreateValidationAsyncInvalidFootballPlayers {
            get {
                return ResourceManager.GetString("CreateValidationAsyncInvalidFootballPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esporte inválido!.
        /// </summary>
        internal static string CreateValidationAsyncInvalidSport {
            get {
                return ResourceManager.GetString("CreateValidationAsyncInvalidSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de jogadores inválido para vôlei. Deve haver no mínimo 6 jogadores num time de vôlei..
        /// </summary>
        internal static string CreateValidationAsyncInvalidVolleyPlayers {
            get {
                return ResourceManager.GetString("CreateValidationAsyncInvalidVolleyPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato inválido..
        /// </summary>
        internal static string InvalidChampionship {
            get {
                return ResourceManager.GetString("InvalidChampionship", resourceCulture);
            }
        }
    }
}
