//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Services.EmailService", typeof(EmailService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Email.
        /// </summary>
        public static string SendConfirmationEmailConfirmacaoDeEmail {
            get {
                return ResourceManager.GetString("SendConfirmationEmailConfirmacaoDeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar email.
        /// </summary>
        public static string SendConfirmationEmailConfirmarEmail {
            get {
                return ResourceManager.GetString("SendConfirmationEmailConfirmarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme seu email.
        /// </summary>
        public static string SendConfirmationEmailConfirmeSeuEmail {
            get {
                return ResourceManager.GetString("SendConfirmationEmailConfirmeSeuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você se cadastrou na plataforma PlayOffs..
        /// </summary>
        public static string SendConfirmationEmailPlayoffs {
            get {
                return ResourceManager.GetString("SendConfirmationEmailPlayoffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize o botão abaixo para confirmar o seu email..
        /// </summary>
        public static string SendConfirmationEmailUseTheButtonBellow {
            get {
                return ResourceManager.GetString("SendConfirmationEmailUseTheButtonBellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar senha.
        /// </summary>
        public static string SendEmailPasswordResetAlterarSenha {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetAlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenciosamente.
        /// </summary>
        public static string SendEmailPasswordResetAtenciosamente {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetAtenciosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe RoDaMo.
        /// </summary>
        public static string SendEmailPasswordResetEquipeRoDaMo {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetEquipeRoDaMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso não consiga utilizar o botão, copie e cole o seguinte link no seu navegador:.
        /// </summary>
        public static string SendEmailPasswordResetLink {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string SendEmailPasswordResetOla {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetOla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinição de senha.
        /// </summary>
        public static string SendEmailPasswordResetRedefinicaoSenha {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetRedefinicaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de alteração de senha.
        /// </summary>
        public static string SendEmailPasswordResetTitulo {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize o botão abaixo para alterar a sua senha..
        /// </summary>
        public static string SendEmailPasswordResetUseTheButton {
            get {
                return ResourceManager.GetString("SendEmailPasswordResetUseTheButton", resourceCulture);
            }
        }
    }
}
