//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Services.TeamService", typeof(TeamService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time já vinculado com esse campeonato.
        /// </summary>
        public static string AddTeamToChampionshipValidationTeamAlreadyLinked {
            get {
                return ResourceManager.GetString("AddTeamToChampionshipValidationTeamAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário passado já é técnico de um time..
        /// </summary>
        public static string CreateValidationAsyncAlreadyCoach {
            get {
                return ResourceManager.GetString("CreateValidationAsyncAlreadyCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário cadastrar um CPF para criar um time..
        /// </summary>
        public static string CreateValidationAsyncCpfNeeded {
            get {
                return ResourceManager.GetString("CreateValidationAsyncCpfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time não vinculado com campeonato.
        /// </summary>
        public static string RemoveTeamFromChampionshipValidationTeamNotLinked {
            get {
                return ResourceManager.GetString("RemoveTeamFromChampionshipValidationTeamNotLinked", resourceCulture);
            }
        }
    }
}
