//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOffsApi.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOffsApi.Resources.Controllers.AuthController", typeof(AuthController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF vinculado com sucesso.
        /// </summary>
        public static string AddCpfCPFVinculadoComSucesso {
            get {
                return ResourceManager.GetString("AddCpfCPFVinculadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ConfirmEmailErro {
            get {
                return ResourceManager.GetString("ConfirmEmailErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao excluir o usuário.
        /// </summary>
        public static string DeleteHouveErroExcluirUsuario {
            get {
                return ResourceManager.GetString("DeleteHouveErroExcluirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluido com sucesso.
        /// </summary>
        public static string DeleteUsuarioExcluidoComSucesso {
            get {
                return ResourceManager.GetString("DeleteUsuarioExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ForgotPasswordErro {
            get {
                return ResourceManager.GetString("ForgotPasswordErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de redefinição de senha realizado..
        /// </summary>
        public static string ForgotPasswordRedefinicaoSenha {
            get {
                return ResourceManager.GetString("ForgotPasswordRedefinicaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme seu email para poder acessar sua conta..
        /// </summary>
        public static string GenerateTokenConfirmeEmail {
            get {
                return ResourceManager.GetString("GenerateTokenConfirmeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário ou senha incorreta..
        /// </summary>
        public static string GenerateTokenNomeInvalido {
            get {
                return ResourceManager.GetString("GenerateTokenNomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não existe.
        /// </summary>
        public static string GetByIdUsuarioNaoExiste {
            get {
                return ResourceManager.GetString("GetByIdUsuarioNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha inválido.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de redefinição de senha inválido..
        /// </summary>
        public static string InvalidPasswordToken {
            get {
                return ResourceManager.GetString("InvalidPasswordToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário deslogado com sucesso.
        /// </summary>
        public static string LogoutUserDeslogadoSucesso {
            get {
                return ResourceManager.GetString("LogoutUserDeslogadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado com sucesso..
        /// </summary>
        public static string RegisterUserCadastroRealizadoSucesso {
            get {
                return ResourceManager.GetString("RegisterUserCadastroRealizadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string RegisterUserErro {
            get {
                return ResourceManager.GetString("RegisterUserErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email de confirmação reenviado.
        /// </summary>
        public static string ResendConfirmEmailEnviado {
            get {
                return ResourceManager.GetString("ResendConfirmEmailEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email de confirmação reenviado.
        /// </summary>
        public static string ResendForgotPasswordEmailDeConfirmacaoReenviado {
            get {
                return ResourceManager.GetString("ResendForgotPasswordEmailDeConfirmacaoReenviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ResetPasswordErro {
            get {
                return ResourceManager.GetString("ResetPasswordErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro autenticando o usuário..
        /// </summary>
        public static string UpdateAccesTokenErroAutenticando {
            get {
                return ResourceManager.GetString("UpdateAccesTokenErroAutenticando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autenticado.
        /// </summary>
        public static string UpdateAccesTokenNaoAutenticado {
            get {
                return ResourceManager.GetString("UpdateAccesTokenNaoAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expirado.
        /// </summary>
        public static string UpdateAccesTokenRefreshTokenExpirado {
            get {
                return ResourceManager.GetString("UpdateAccesTokenRefreshTokenExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token atualizado.
        /// </summary>
        public static string UpdateAccesTokenTokenAtualizado {
            get {
                return ResourceManager.GetString("UpdateAccesTokenTokenAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string UserAlreadyExistsErro {
            get {
                return ResourceManager.GetString("UserAlreadyExistsErro", resourceCulture);
            }
        }
    }
}
